# DVessentials

# MySQL connection (required)
use-mysql: true
table-prefix: NKtrader_
host: localhost
port: 3306
dbName: dev_minecraft
user: root
password: 


# Options

# The same name gave to Bungee config
server-name: 'world'