name: NKtrader
version: ${project.version}
main: fr.darkvodou.NKtrader.NKtrader
authors: [ Darkvodou ]
description: Trade plugin
commands:
  addtrader:
    description: "add a new trader block or entity"
    usage: /<command> <entity|block> [-n <name>] [-w <world> <x> <y> <z>]
